In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("C:/Users/YarKhan/Desktop/DeepLearning/train.csv")
data

v.id  on road old  on road now  years      km  rating  condition  \
0       1       535651       798186      3   78945       1          2   
1       2       591911       861056      6  117220       5          9   
2       3       686990       770762      2  132538       2          8   
3       4       573999       722381      4  101065       4          3   
4       5       691388       811335      6   61559       3          9   
..    ...          ...          ...    ...     ...     ...        ...   
995   996       633238       743850      5  125092       1          6   
996   997       599626       848195      4   83370       2          9   
997   998       646344       842733      7   86722       1          8   
998   999       535559       732439      2  140478       4          5   
999  1000       590105       779743      5   67295       4          2   

     economy  top speed   hp  torque  current price  
0         14        177   73     123       351318.0  
1          9        148   74      95       285001.5  
2         15        181   53      97       215386.0  
3         11        197   54     116       244295.5  
4         12        160   53     105       531114.5  
..       ...        ...  ...     ...            ...  
995       11        171   95      97       190744.0  
996       14        161  101     120       419748.0  
997        9        196  113      89       405871.0  
998        9        184  112     128        74398.0  
999        8        199   99      96       414938.5  

[1000 rows x 12 columns]

In [5]:
data.shape

(1000, 12)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   v.id           1000 non-null   int64  
 1   on road old    1000 non-null   int64  
 2   on road now    1000 non-null   int64  
 3   years          1000 non-null   int64  
 4   km             1000 non-null   int64  
 5   rating         1000 non-null   int64  
 6   condition      1000 non-null   int64  
 7   economy        1000 non-null   int64  
 8   top speed      1000 non-null   int64  
 9   hp             1000 non-null   int64  
 10  torque         1000 non-null   int64  
 11  current price  1000 non-null   float64
dtypes: float64(1), int64(11)
memory usage: 93.9 KB


In [13]:
data.isnull().sum()

v.id             0
on road old      0
on road now      0
years            0
km               0
rating           0
condition        0
economy          0
top speed        0
hp               0
torque           0
current price    0
dtype: int64

In [20]:
data.count()

v.id             1000
on road old      1000
on road now      1000
years            1000
km               1000
rating           1000
condition        1000
economy          1000
top speed        1000
hp               1000
torque           1000
current price    1000
dtype: int64

In [12]:
data.nunique()

v.id             1000
on road old       998
on road now       998
years               6
km                997
rating              5
condition          10
economy             8
top speed          66
hp                 71
torque             73
current price    1000
dtype: int64

In [16]:
data.describe()

v.id    on road old  on road now        years             km  \
count  1000.000000    1000.000000    1000.0000  1000.000000    1000.000000   
mean    500.500000  601648.286000  799131.3970     4.561000  100274.430000   
std     288.819436   58407.246204   57028.9502     1.719079   29150.463233   
min       1.000000  500265.000000  700018.0000     2.000000   50324.000000   
25%     250.750000  548860.500000  750997.7500     3.000000   74367.500000   
50%     500.500000  601568.000000  798168.0000     5.000000  100139.500000   
75%     750.250000  652267.250000  847563.2500     6.000000  125048.000000   
max    1000.000000  699859.000000  899797.0000     7.000000  149902.000000   

            rating    condition      economy   top speed          hp  \
count  1000.000000  1000.000000  1000.000000  1000.00000  1000.00000   
mean      2.988000     5.592000    11.625000   166.89300    84.54600   
std       1.402791     2.824449     2.230549    19.28838    20.51694   
min       1.000000     1.000000     8.000000   135.00000    50.00000   
25%       2.000000     3.000000    10.000000   150.00000    67.00000   
50%       3.000000     6.000000    12.000000   166.00000    84.00000   
75%       4.000000     8.000000    13.000000   184.00000   102.00000   
max       5.000000    10.000000    15.000000   200.00000   120.00000   

            torque  current price  
count  1000.000000     1000.00000  
mean    103.423000   308520.24250  
std      21.058716   126073.25915  
min      68.000000    28226.50000  
25%      85.000000   206871.75000  
50%     104.000000   306717.75000  
75%     121.000000   414260.87500  
max     140.000000   584267.50000

In [19]:
data.columns

Index(['v.id', 'on road old', 'on road now', 'years', 'km', 'rating',
       'condition', 'economy', 'top speed', 'hp', 'torque', 'current price'],
      dtype='object')

In [25]:
data = data.drop("v.id", axis = 1)

In [26]:
data

on road old  on road now  years      km  rating  condition  economy  \
0         535651       798186      3   78945       1          2       14   
1         591911       861056      6  117220       5          9        9   
2         686990       770762      2  132538       2          8       15   
3         573999       722381      4  101065       4          3       11   
4         691388       811335      6   61559       3          9       12   
..           ...          ...    ...     ...     ...        ...      ...   
995       633238       743850      5  125092       1          6       11   
996       599626       848195      4   83370       2          9       14   
997       646344       842733      7   86722       1          8        9   
998       535559       732439      2  140478       4          5        9   
999       590105       779743      5   67295       4          2        8   

     top speed   hp  torque  current price  
0          177   73     123       351318.0  
1          148   74      95       285001.5  
2          181   53      97       215386.0  
3          197   54     116       244295.5  
4          160   53     105       531114.5  
..         ...  ...     ...            ...  
995        171   95      97       190744.0  
996        161  101     120       419748.0  
997        196  113      89       405871.0  
998        184  112     128        74398.0  
999        199   99      96       414938.5  

[1000 rows x 11 columns]

In [27]:
tensor_df = tf.constant(data, dtype = tf.float32)
tensor_df

<tf.Tensor: shape=(1000, 11), dtype=float32, numpy=
array([[5.356510e+05, 7.981860e+05, 3.000000e+00, ..., 7.300000e+01,
        1.230000e+02, 3.513180e+05],
       [5.919110e+05, 8.610560e+05, 6.000000e+00, ..., 7.400000e+01,
        9.500000e+01, 2.850015e+05],
       [6.869900e+05, 7.707620e+05, 2.000000e+00, ..., 5.300000e+01,
        9.700000e+01, 2.153860e+05],
       ...,
       [6.463440e+05, 8.427330e+05, 7.000000e+00, ..., 1.130000e+02,
        8.900000e+01, 4.058710e+05],
       [5.355590e+05, 7.324390e+05, 2.000000e+00, ..., 1.120000e+02,
        1.280000e+02, 7.439800e+04],
       [5.901050e+05, 7.797430e+05, 5.000000e+00, ..., 9.900000e+01,
        9.600000e+01, 4.149385e+05]], dtype=float32)>

In [28]:
tensor_df = tf.random.shuffle(tensor_df)
tensor_df

<tf.Tensor: shape=(1000, 11), dtype=float32, numpy=
array([[5.970160e+05, 7.878040e+05, 6.000000e+00, ..., 8.000000e+01,
        7.900000e+01, 3.926355e+05],
       [5.040160e+05, 7.919330e+05, 4.000000e+00, ..., 1.120000e+02,
        9.600000e+01, 2.216920e+05],
       [5.161580e+05, 7.784500e+05, 7.000000e+00, ..., 5.200000e+01,
        1.000000e+02, 8.723450e+04],
       ...,
       [6.990230e+05, 8.386540e+05, 7.000000e+00, ..., 9.400000e+01,
        1.390000e+02, 2.758375e+05],
       [6.581770e+05, 7.598790e+05, 7.000000e+00, ..., 7.400000e+01,
        1.190000e+02, 4.686660e+05],
       [6.245380e+05, 7.742950e+05, 5.000000e+00, ..., 9.900000e+01,
        1.130000e+02, 1.809120e+05]], dtype=float32)>

In [31]:
X = tensor_df[:, 2:-1]
X

<tf.Tensor: shape=(1000, 8), dtype=float32, numpy=
array([[6.00000e+00, 7.44440e+04, 5.00000e+00, ..., 1.88000e+02,
        8.00000e+01, 7.90000e+01],
       [4.00000e+00, 1.06653e+05, 4.00000e+00, ..., 1.94000e+02,
        1.12000e+02, 9.60000e+01],
       [7.00000e+00, 1.45395e+05, 3.00000e+00, ..., 1.88000e+02,
        5.20000e+01, 1.00000e+02],
       ...,
       [7.00000e+00, 1.22196e+05, 1.00000e+00, ..., 1.94000e+02,
        9.40000e+01, 1.39000e+02],
       [7.00000e+00, 7.05640e+04, 1.00000e+00, ..., 1.76000e+02,
        7.40000e+01, 1.19000e+02],
       [5.00000e+00, 1.33782e+05, 5.00000e+00, ..., 1.86000e+02,
        9.90000e+01, 1.13000e+02]], dtype=float32)>

In [32]:
y = tensor_df[:, -1]
y = tf.expand_dims(y, axis = -1)
y

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[392635.5],
       [221692. ],
       [ 87234.5],
       [424305. ],
       [385556.5],
       [172032.5],
       [213768.5],
       [291810. ],
       [153371.5],
       [206836.5],
       [350647.5],
       [304445. ],
       [405871. ],
       [352345. ],
       [179711.5],
       [457463. ],
       [315925. ],
       [315131.5],
       [367734.5],
       [427132.5],
       [174399. ],
       [212553.5],
       [452633. ],
       [315866.5],
       [360008. ],
       [172859.5],
       [203811.5],
       [227669. ],
       [238638.5],
       [112864.5],
       [420083. ],
       [404800.5],
       [347784.5],
       [190949. ],
       [435007.5],
       [299609. ],
       [382794.5],
       [417940. ],
       [438032.5],
       [160597.5],
       [458537. ],
       [458463.5],
       [ 53040. ],
       [344405.5],
       [497572.5],
       [153991. ],
       [443528. ],
       [220518. ],
       [267953.5],
       [389610. ],

In [33]:
from tensorflow.keras.layers import Normalization

In [34]:
normalizer = Normalization()
normalizer.adapt(X)
normalizer(X)

<tf.Tensor: shape=(1000, 8), dtype=float32, numpy=
array([[ 0.83749473, -0.88655   ,  1.4350008 , ...,  1.0948333 ,
        -0.22168264, -1.1603374 ],
       [-0.32650062,  0.21892546,  0.72177976, ...,  1.406057  ,
         1.3387846 , -0.35266685],
       [ 1.4194925 ,  1.5486262 ,  0.00855871, ...,  1.0948333 ,
        -1.5870914 , -0.1626267 ],
       ...,
       [ 1.4194925 ,  0.75239146, -1.4178834 , ...,  1.406057  ,
         0.46102175,  1.6902648 ],
       [ 1.4194925 , -1.0197191 , -1.4178834 , ...,  0.47238562,
        -0.51427025,  0.740064  ],
       [ 0.25549707,  1.1500455 ,  1.4350008 , ...,  0.99109197,
         0.7048448 ,  0.4550038 ]], dtype=float32)>

In [39]:
model = tf.keras.Sequential([normalizer, tf.keras.layers.Dense(1)])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization (Normalizatio  (None, 8)                17        
 n)                                                              
                                                                 
 dense (Dense)               (None, 1)                 9         
                                                                 
Total params: 26
Trainable params: 9
Non-trainable params: 17
_________________________________________________________________


In [45]:
!pip install pydot

In [47]:
!pip install graphviz

In [50]:
import pydot
import graphviz

In [52]:
tf.keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [ ]:
model.compile(loss = tf.keras.losses.mse, )